/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 19-Nov-2020 19:25:11 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE mine_view
(
	identifier varchar(255) NOT NULL,
	name varchar(255) NULL,
	status varchar(255) NOT NULL,
	commodity varchar(255) NULL,
	owner varchar(255) NULL,
	"startDate" varchar(255) NULL,
	"endDate" varchar(255) NULL,
	"observationMethod" varchar(255) NULL,
	"positionalAccuracy" varchar(255) NULL,
	source varchar(255) NULL,
	status_uri varchar(255) NOT NULL,
	"representativeCommodity_uri" varchar(255) NULL,
	specification_uri varchar(255) NULL,
	shape geometry(point) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE mine_view ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY (identifier)
;
